; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 16
.func_main:
  mov rax, 10
  mov rsp, rbp
  pop rbp
  ret
.main_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall