; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global is_even
is_even:
  push rbp
  mov rbp, rsp
  sub rsp, 32
  mov [rbp-8], rdi
.func_is_even:
  mov rax, [rbp-8]
  cqo
  mov rcx, 2
  idiv rcx
  mov [rbp-16], rdx
  mov rax, [rbp-16]
  cmp rax, 0
  sete al
  movzx rax, al
  mov rsp, rbp
  pop rbp
  ret
.is_even_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global do_nothing
do_nothing:
  push rbp
  mov rbp, rsp
  sub rsp, 112
.func_do_nothing:
  xor eax, eax
  mov [rbp-8], rax
  xor eax, eax
  mov [rbp-16], rax
.for_cond_1:
  cmp rax, 5
  setl al
  movzx rax, al
  cmp rax, 0
  jne .for_body_2
  jmp .for_end_4
.for_body_2:
  mov rdi, [rbp-16]
  call is_even
  cmp rax, 0
  je .end_if_6
.then_5:
  mov rax, [rbp-8]
  add rax, qword [rbp-16]
  mov [rbp-8], rax
.end_if_6:
.for_update_3:
  mov rax, [rbp-16]
  inc rax
  mov [rbp-16], rax
  jmp .for_cond_1
.for_end_4:
.do_nothing_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 16
.func_main:
  call do_nothing
  mov [rbp-8], rax
.main_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall