; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 16
  push rbx
  push r12
  push r13
  push r14
  push r15
.func_main:
.for_cond_1:
  mov rax, r12
  cmp rax, 5
  setl al
  movzx rax, al
  mov r13, rax
  mov rax, r13
  cmp rax, 0
  jne .for_body_2
  jmp .for_end_4
.for_body_2:
  mov rax, r12
  cqo
  mov rcx, 2
  idiv rcx
  mov r15, rdx
  mov rax, r15
  cmp rax, 0
  sete al
  movzx rax, al
  mov r14, rax
  mov rax, r14
  cmp rax, 0
  je .end_if_6
.then_5:
  mov rax, rbx
  add rax, r12
  mov r13, rax
  mov rbx, r13
.end_if_6:
.for_update_3:
  mov rax, r12
  inc rax
  mov r13, rax
  mov r12, r13
  jmp .for_cond_1
.for_end_4:
  mov rax, rbx
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret
.main_epilogue_fallback:
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall