; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 112
.func_main:
.for_cond_1:
  xor eax, eax
  mov [rbp-8], rax
  xor eax, eax
  mov [rbp-16], rax
  cmp rax, 5
  setl al
  movzx rax, al
  cmp rax, 0
  jne .for_body_2
  jmp .for_end_4
.for_body_2:
  mov rax, [rbp-16]
  cqo
  mov rcx, 2
  idiv rcx
  mov [rbp-32], rdx
  mov rax, [rbp-32]
  cmp rax, 0
  sete al
  movzx rax, al
  cmp rax, 0
  je .end_if_6
.then_5:
  mov rax, [rbp-8]
  add rax, qword [rbp-16]
  mov [rbp-8], rax
.end_if_6:
.for_update_3:
  mov rax, [rbp-16]
  inc rax
  mov [rbp-16], rax
  jmp .for_cond_1
.for_end_4:
  mov rax, [rbp-8]
  mov rsp, rbp
  pop rbp
  ret
.main_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall