; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 112
.func_main:
  xor eax, eax
  mov [rbp-8], rax
  mov rax, 10
  mov [rbp-16], rax
  mov rax, 1
  mov [rbp-24], rax
.while_cond_1:
  cmp rax, [rbp-16]
  setle al
  movzx rax, al
  cmp rax, 0
  jne .while_body_2
  jmp .while_end_3
.while_body_2:
  mov rax, [rbp-24]
  cqo
  mov rcx, 2
  idiv rcx
  mov [rbp-40], rdx
  mov rax, [rbp-40]
  cmp rax, 0
  sete al
  movzx rax, al
  cmp rax, 0
  je .else_6
.else_6:
  jmp .end_if_5
.then_4:
  mov rax, [rbp-8]
  add rax, qword [rbp-24]
  mov [rbp-8], rax
.end_if_5:
  mov rax, [rbp-24]
  inc rax
  mov [rbp-24], rax
  jmp .while_cond_1
.while_end_3:
  mov rax, [rbp-8]
  mov rsp, rbp
  pop rbp
  ret
.main_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall