; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 80
  push rbx
  push r12
  push r13
  push r14
  push r15
.func_main:
.while_cond_1:
  mov [rbp-8], r12
  mov r13, r14
  mov rax, [rbp-24]
  cmp rax, r13
  setle al
  movzx rax, al
  mov r15, rax
  mov rax, r15
  cmp rax, 0
  jne .while_body_2
  jmp .while_end_3
.while_body_2:
  mov rax, [rbp-24]
  cqo
  mov rcx, 2
  idiv rcx
  mov rbx, rdx
  mov rax, rbx
  cmp rax, 0
  sete al
  movzx rax, al
  mov r15, rax
  mov rax, r15
  cmp rax, 0
  je .else_6
.else_6:
.end_if_5:
  mov r12, [rbp-8]
  mov r14, r13
  mov rbx, [rbp-24]
  mov rax, rbx
  inc rax
  mov r12, rax
  mov [rbp-24], r12
  jmp .while_cond_1
.while_end_3:
  mov rax, [rbp-8]
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret
.main_epilogue_fallback:
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall