; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 64
  push rbx
  push r12
  push r13
  push r14
  push r15
.func_main:
  lea rax, [rbp-40]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov rcx, 10
  mov [r12], rcx
  lea rax, [rbp-40]
  mov rcx, 1
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov rcx, 20
  mov [r13], rcx
  lea rax, [rbp-40]
  mov rcx, 2
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov rcx, 30
  mov [r14], rcx
  lea rax, [rbp-40]
  mov rcx, 3
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rcx, 40
  mov [r15], rcx
  lea rax, [rbp-40]
  mov rcx, 4
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov rcx, 50
  mov [r12], rcx
  xor eax, eax
  mov [rbp-48], rax
  mov r13, 0
.for_cond_1:
  mov rax, r13
  cmp rax, 5
  setl al
  movzx rax, al
  mov r12, rax
  mov rax, r12
  cmp rax, 0
  jne .for_body_2
  jmp .for_end_4
.for_body_2:
  lea rax, [rbp-40]
  mov rcx, r13
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov r15, [r14]
  mov rax, [rbp-48]
  add rax, r15
  mov r12, rax
  mov [rbp-48], r12
.for_update_3:
  mov rax, r13
  inc rax
  mov rbx, rax
  mov r13, rbx
  jmp .for_cond_1
.for_end_4:
  mov rdi, str_5
  mov rsi, [rbp-48]
  mov eax, 0
  call printf
  mov rax, [rbp-48]
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret
.main_epilogue_fallback:
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall

section .data
str_5: db `Total sum of array: %d\n`, 0