; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 80
.func_main:
  mov rdi, str_1
  mov eax, 0
  call printf
  mov rdi, str_2
  mov eax, 0
  call printf
  mov rdi, 40
  call malloc
  mov [rbp-32], rax
  mov rdi, str_3
  mov rsi, [rbp-32]
  mov eax, 0
  call printf
  mov rdi, [rbp-32]
  call free
  mov rdi, str_4
  mov eax, 0
  call printf
  mov rdi, str_5
  mov eax, 0
  call printf
.main_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall

section .data
str_1: db `Testing external functions:\n`, 0
str_2: db `Array allocation test...\n`, 0
str_3: db `Allocated 40 bytes at address: %d\n`, 0
str_4: db `Freed memory.\n`, 0
str_5: db `Done!\n`, 0