; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 160
.func_main:
  lea rax, [rbp-40]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov rcx, 10
  mov [rax], rcx
  lea rax, [rbp-40]
  mov rcx, 1
  shl rcx, 3
  add rax, rcx
  mov rcx, 20
  mov [rax], rcx
  lea rax, [rbp-40]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov rcx, [rax]
  mov [rbp-72], rcx
  lea rax, [rbp-40]
  mov rcx, 1
  shl rcx, 3
  add rax, rcx
  mov rcx, [rax]
  mov [rbp-88], rcx
  mov rax, [rbp-72]
  add rax, qword [rbp-88]
  lea rax, [rbp-128]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov rcx, 1
  mov [rax], rcx
  lea rax, [rbp-128]
  mov rcx, 1
  shl rcx, 3
  add rax, rcx
  mov rcx, 2
  mov [rax], rcx
  lea rax, [rbp-128]
  mov rcx, 2
  shl rcx, 3
  add rax, rcx
  mov rcx, 3
  mov [rax], rcx
.main_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall