; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 80
  push rbx
  push r12
  push r13
  push r14
  push r15
.func_main:
  lea rax, [rbp-40]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov rcx, 10
  mov [r12], rcx
  lea rax, [rbp-40]
  mov rcx, 1
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov rcx, 20
  mov [r13], rcx
  lea rax, [rbp-40]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov r15, [r14]
  lea rax, [rbp-40]
  mov rcx, 1
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov r13, [r12]
  mov rax, r15
  add rax, r13
  mov r14, rax
  mov rbx, r14
  lea rax, [rbp-64]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rcx, 1
  mov [r15], rcx
  lea rax, [rbp-64]
  mov rcx, 1
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov rcx, 2
  mov [r13], rcx
  lea rax, [rbp-64]
  mov rcx, 2
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov rcx, 3
  mov [r14], rcx
.main_epilogue_fallback:
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall