; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 192
  push rbx
  push r12
  push r13
  push r14
  push r15
.func_main:
  mov rdi, str_1
  mov eax, 0
  call printf
  mov rdi, str_2
  mov rsi, 100
  mov rdx, 100
  mov eax, 0
  call printf
  mov rdi, str_3
  mov eax, 0
  call printf
.for_cond_4:
  mov rax, [rbp-32]
  cmp rax, [rbp-96]
  setl al
  movzx rax, al
  mov rbx, rax
  mov rax, rbx
  cmp rax, 0
  jne .for_body_5
  jmp .for_end_7
.for_body_5:
.for_cond_8:
  mov rax, [rbp-120]
  cmp rax, [rbp-40]
  setl al
  movzx rax, al
  mov r12, rax
  mov rax, r12
  cmp rax, 0
  jne .for_body_9
  jmp .for_end_11
.for_body_9:
  mov rax, [rbp-120]
  sub rax, qword [rbp-112]
  mov r13, rax
  mov [rbp-144], r13
  mov rax, [rbp-32]
  sub rax, qword [rbp-104]
  mov r14, rax
  mov [rbp-152], r14
  mov rax, [rbp-144]
  imul rax, qword [rbp-144]
  mov r15, rax
  mov rax, [rbp-152]
  imul rax, qword [rbp-152]
  mov rbx, rax
  mov rax, r15
  add rax, rbx
  mov r12, rax
  mov [rbp-160], r12
  mov rax, [rbp-160]
  cmp rax, [rbp-80]
  setl al
  movzx rax, al
  mov r13, rax
  mov rax, r13
  cmp rax, 0
  je .else_14
.else_14:
  mov rdi, str_16
  mov eax, 0
  call printf
  jmp .end_if_13
.then_12:
  mov rdi, str_15
  mov eax, 0
  call printf
.end_if_13:
.for_update_10:
  mov rax, [rbp-120]
  inc rax
  mov r14, rax
  mov [rbp-120], r14
  jmp .for_cond_8
.for_end_11:
  mov rdi, str_17
  mov eax, 0
  call printf
.for_update_6:
  mov rax, [rbp-32]
  inc rax
  mov r15, rax
  mov [rbp-32], r15
  jmp .for_cond_4
.for_end_7:
.main_epilogue_fallback:
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall

section .data
str_1: db `P3\n`, 0
str_2: db `%d %d\n`, 0
str_3: db `255\n`, 0
str_15: db `255 0 0 `, 0
str_16: db `0 0 0 `, 0
str_17: db `\n`, 0