; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 456
  push rbx
  push r12
  push r13
  push r14
  push r15
.func_main:
  lea rax, [rbp-80]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov rcx, 64
  mov [rbx], rcx
  lea rax, [rbp-80]
  mov rcx, 1
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov rcx, 34
  mov [r12], rcx
  lea rax, [rbp-80]
  mov rcx, 2
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov rcx, 25
  mov [r13], rcx
  lea rax, [rbp-80]
  mov rcx, 3
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov rcx, 12
  mov [r14], rcx
  lea rax, [rbp-80]
  mov rcx, 4
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rcx, 22
  mov [r15], rcx
  lea rax, [rbp-80]
  mov rcx, 5
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov rcx, 11
  mov [rbx], rcx
  lea rax, [rbp-80]
  mov rcx, 6
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov rcx, 90
  mov [r12], rcx
  lea rax, [rbp-80]
  mov rcx, 7
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov rcx, 45
  mov [r13], rcx
  lea rax, [rbp-80]
  mov rcx, 8
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov rcx, 7
  mov [r14], rcx
  lea rax, [rbp-80]
  mov rcx, 9
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rcx, 53
  mov [r15], rcx
  mov rdi, str_1
  mov eax, 0
  call printf
  mov [rbp-88], rax
  mov rdi, str_2
  mov eax, 0
  call printf
  mov [rbp-88], rax
  xor eax, eax
  mov [rbp-88], rax
.for_cond_3:
  cmp rax, 10
  setl al
  movzx rax, al
  mov rbx, rax
  mov rax, rbx
  cmp rax, 0
  jne .for_body_4
  jmp .for_end_6
.for_body_4:
  lea rax, [rbp-80]
  mov rcx, [rbp-88]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov r13, [r12]
  mov rdi, str_7
  mov rsi, r13
  mov eax, 0
  call printf
  mov [rbp-192], rax
.for_update_5:
  mov rax, [rbp-88]
  inc rax
  mov r14, rax
  mov [rbp-88], r14
  jmp .for_cond_3
.for_end_6:
  mov rdi, str_8
  mov eax, 0
  call printf
  mov [rbp-192], rax
  mov rax, 10
  mov [rbp-192], rax
  xor eax, eax
  mov [rbp-200], rax
.for_cond_9:
  mov rax, [rbp-192]
  dec rax
  mov r15, rax
  mov rax, [rbp-200]
  cmp rax, r15
  setl al
  movzx rax, al
  mov rbx, rax
  mov rax, rbx
  cmp rax, 0
  jne .for_body_10
  jmp .for_end_12
.for_body_10:
  xor eax, eax
  mov [rbp-256], rax
.for_cond_13:
  mov rax, [rbp-192]
  dec rax
  mov r12, rax
  mov rax, r12
  sub rax, qword [rbp-200]
  mov r13, rax
  mov rax, [rbp-256]
  cmp rax, r13
  setl al
  movzx rax, al
  mov r14, rax
  mov rax, r14
  cmp rax, 0
  jne .for_body_14
  jmp .for_end_16
.for_body_14:
  lea rax, [rbp-80]
  mov rcx, [rbp-256]
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rbx, [r15]
  mov rax, [rbp-256]
  inc rax
  mov r12, rax
  lea rax, [rbp-80]
  mov rcx, r12
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov r14, [r13]
  mov rax, rbx
  cmp rax, r14
  setg al
  movzx rax, al
  mov r15, rax
  mov rax, r15
  cmp rax, 0
  je .end_if_18
.then_17:
  lea rax, [rbp-80]
  mov rcx, [rbp-256]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov r13, [r12]
  mov [rbp-296], r13
  mov rax, [rbp-256]
  inc rax
  mov rbx, rax
  lea rax, [rbp-80]
  mov rcx, rbx
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov r15, [r14]
  lea rax, [rbp-80]
  mov rcx, [rbp-256]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov [r12], r15
  mov rax, [rbp-256]
  inc rax
  mov r13, rax
  lea rax, [rbp-80]
  mov rcx, r13
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov rcx, [rbp-296]
  mov [rbx], rcx
.end_if_18:
.for_update_15:
  mov rax, [rbp-256]
  inc rax
  mov r14, rax
  mov [rbp-256], r14
  jmp .for_cond_13
.for_end_16:
.for_update_11:
  mov rax, [rbp-200]
  inc rax
  mov r15, rax
  mov [rbp-200], r15
  jmp .for_cond_9
.for_end_12:
  mov rdi, str_19
  mov eax, 0
  call printf
  xor eax, eax
  mov [rbp-88], rax
.for_cond_20:
  cmp rax, 10
  setl al
  movzx rax, al
  mov r12, rax
  mov rax, r12
  cmp rax, 0
  jne .for_body_21
  jmp .for_end_23
.for_body_21:
  lea rax, [rbp-80]
  mov rcx, [rbp-88]
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov rbx, [r13]
  mov rdi, str_24
  mov rsi, rbx
  mov eax, 0
  call printf
.for_update_22:
  mov rax, [rbp-88]
  inc rax
  mov r14, rax
  mov [rbp-88], r14
  jmp .for_cond_20
.for_end_23:
  mov rdi, str_25
  mov eax, 0
  call printf
  mov [rbp-88], rax
  mov rdi, str_26
  mov eax, 0
  call printf
  xor eax, eax
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret
.main_epilogue_fallback:
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall

section .data
str_1: db `Bubble Sort\n`, 0
str_2: db `Before: `, 0
str_7: db `%d `, 0
str_8: db `\n`, 0
str_19: db `After:  `, 0
str_24: db `%d `, 0
str_25: db `\n`, 0
str_26: db `Bubble sort complete!\n`, 0