; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 128
.func_main:
  mov rax, 200
  mov [rbp-8], rax
  mov [rbp-16], rax
.while_cond_1:
  ; PHI t3_3 handled via aliasing or moves
  ; PHI i_4 handled via aliasing or moves
  ; PHI sum_4 handled via aliasing or moves
  ; PHI t4_3 handled via aliasing or moves
  mov rax, [rbp-32]
  cmp rax, 0
  setl al
  movzx rax, al
  mov [rbp-56], rax
  cmp rax, 0
  jne .while_body_2
.while_end_3:
  ; PHI sum_6 handled via aliasing or moves
  ; PHI i_6 handled via aliasing or moves
  ; PHI t2_3 handled via aliasing or moves
  ; PHI t4_5 handled via aliasing or moves
  ; PHI t3_5 handled via aliasing or moves
  mov rax, [rbp-16]
  add rax, qword [rbp-40]
  mov [rbp-72], rax
  mov [rbp-80], rax
  cmp rax, 200
  sete al
  movzx rax, al
  mov [rbp-88], rax
  cmp rax, 0
  je .else_6
.then_4:
  mov rax, [rbp-80]
  mov rsp, rbp
  pop rbp
  ret
  jmp .end_if_5
.else_6:
  mov rax, 1
  neg rax
  mov [rbp-96], rax
  mov rsp, rbp
  pop rbp
  ret
.end_if_5:
.while_body_2:
  mov rax, [rbp-16]
  mov [rbp-104], rax
  mov rax, 1
  mov [rbp-112], rax
  jmp .while_cond_1
.main_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall