; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 1760
  push rbx
  push r12
  push r13
  push r14
  push r15
.func_main:
  lea rax, [rbp-80]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov rcx, 64
  mov [rbx], rcx
  lea rax, [rbp-80]
  mov rcx, 1
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov rcx, 34
  mov [r12], rcx
  lea rax, [rbp-80]
  mov rcx, 2
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov rcx, 25
  mov [r13], rcx
  lea rax, [rbp-80]
  mov rcx, 3
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov rcx, 12
  mov [r14], rcx
  lea rax, [rbp-80]
  mov rcx, 4
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rcx, 22
  mov [r15], rcx
  lea rax, [rbp-80]
  mov rcx, 5
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov rcx, 11
  mov [rbx], rcx
  lea rax, [rbp-80]
  mov rcx, 6
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov rcx, 90
  mov [r12], rcx
  lea rax, [rbp-80]
  mov rcx, 7
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov rcx, 45
  mov [r13], rcx
  lea rax, [rbp-80]
  mov rcx, 8
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov rcx, 7
  mov [r14], rcx
  lea rax, [rbp-80]
  mov rcx, 9
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rcx, 53
  mov [r15], rcx
  mov rdi, str_1
  mov eax, 0
  call printf
  mov rdi, str_2
  mov eax, 0
  call printf
  xor eax, eax
  mov [rbp-104], rax
.for_cond_3:
  cmp rax, 10
  setl al
  movzx rax, al
  mov rbx, rax
  mov rax, rbx
  cmp rax, 0
  jne .for_body_4
  jmp .for_end_6
.for_body_4:
  lea rax, [rbp-80]
  mov rcx, [rbp-104]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov r13, [r12]
  mov rdi, str_7
  mov rsi, r13
  mov eax, 0
  call printf
.for_update_5:
  mov rax, [rbp-104]
  inc rax
  mov r14, rax
  mov [rbp-104], r14
  jmp .for_cond_3
.for_end_6:
  mov rdi, str_8
  mov eax, 0
  call printf
  xor eax, eax
  mov [rbp-736], rax
  lea rax, [rbp-472]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rcx, 0
  mov [r15], rcx
  lea rax, [rbp-728]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov rcx, 9
  mov [rbx], rcx
  mov rax, 1
  mov [rbp-736], rax
  cmp rax, 0
  setg al
  movzx rax, al
  mov r12, rax
  mov rax, r12
  cmp rax, 0
  jne .while_peel_9
  jmp .while_end_12
.while_peel_9:
  mov rax, [rbp-736]
  dec rax
  mov r13, rax
  mov [rbp-736], r13
  lea rax, [rbp-472]
  mov rcx, [rbp-736]
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov r15, [r14]
  mov [rbp-744], r15
  lea rax, [rbp-728]
  mov rcx, [rbp-736]
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov r12, [rbx]
  mov [rbp-752], r12
  mov rax, [rbp-744]
  cmp rax, [rbp-752]
  setl al
  movzx rax, al
  mov r13, rax
  mov rax, r13
  cmp rax, 0
  je .end_if_14
.then_13:
  lea rax, [rbp-80]
  mov rcx, [rbp-752]
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov r15, [r14]
  mov [rbp-760], r15
  mov rax, [rbp-744]
  dec rax
  mov rbx, rax
  mov [rbp-104], rbx
  mov rax, [rbp-744]
  mov [rbp-768], rax
  cmp rax, [rbp-752]
  setl al
  movzx rax, al
  mov r12, rax
  mov rax, r12
  cmp rax, 0
  jne .while_peel_15
  jmp .while_end_18
.while_peel_15:
  lea rax, [rbp-80]
  mov rcx, [rbp-768]
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov r14, [r13]
  mov rax, r14
  cmp rax, [rbp-760]
  setle al
  movzx rax, al
  mov r15, rax
  mov rax, r15
  cmp rax, 0
  je .end_if_20
.then_19:
  mov rax, [rbp-104]
  inc rax
  mov rbx, rax
  mov [rbp-104], rbx
  lea rax, [rbp-80]
  mov rcx, [rbp-104]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov r13, [r12]
  mov [rbp-776], r13
  lea rax, [rbp-80]
  mov rcx, [rbp-768]
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov r15, [r14]
  lea rax, [rbp-80]
  mov rcx, [rbp-104]
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov [rbx], r15
  lea rax, [rbp-80]
  mov rcx, [rbp-768]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov rcx, [rbp-776]
  mov [r12], rcx
.end_if_20:
  mov rax, [rbp-768]
  inc rax
  mov r13, rax
  mov [rbp-768], r13
.while_cond_16:
  mov rax, [rbp-768]
  cmp rax, [rbp-752]
  setl al
  movzx rax, al
  mov r14, rax
  mov rax, r14
  cmp rax, 0
  jne .while_body_17
  jmp .while_end_18
.while_body_17:
  lea rax, [rbp-80]
  mov rcx, [rbp-768]
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rbx, [r15]
  mov rax, rbx
  cmp rax, [rbp-760]
  setle al
  movzx rax, al
  mov r12, rax
  mov rax, r12
  cmp rax, 0
  je .end_if_22
.then_21:
  mov rax, [rbp-104]
  inc rax
  mov r13, rax
  mov [rbp-104], r13
  lea rax, [rbp-80]
  mov rcx, [rbp-104]
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov r15, [r14]
  mov [rbp-776], r15
  lea rax, [rbp-80]
  mov rcx, [rbp-768]
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov r12, [rbx]
  lea rax, [rbp-80]
  mov rcx, [rbp-104]
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov [r13], r12
  lea rax, [rbp-80]
  mov rcx, [rbp-768]
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov rcx, [rbp-776]
  mov [r14], rcx
.end_if_22:
  mov rax, [rbp-768]
  inc rax
  mov r15, rax
  mov [rbp-768], r15
  jmp .while_cond_16
.while_end_18:
  mov rax, [rbp-104]
  inc rax
  mov rbx, rax
  mov [rbp-1192], rbx
  lea rax, [rbp-80]
  mov rcx, [rbp-1192]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov r13, [r12]
  mov [rbp-784], r13
  lea rax, [rbp-80]
  mov rcx, [rbp-752]
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov r15, [r14]
  lea rax, [rbp-80]
  mov rcx, [rbp-1192]
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov [rbx], r15
  lea rax, [rbp-80]
  mov rcx, [rbp-752]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov rcx, [rbp-784]
  mov [r12], rcx
  mov rax, [rbp-1192]
  dec rax
  mov r13, rax
  mov rax, [rbp-744]
  cmp rax, r13
  setl al
  movzx rax, al
  mov r14, rax
  mov rax, r14
  cmp rax, 0
  je .end_if_24
.then_23:
  lea rax, [rbp-472]
  mov rcx, [rbp-736]
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rcx, [rbp-744]
  mov [r15], rcx
  mov rax, [rbp-1192]
  dec rax
  mov rbx, rax
  lea rax, [rbp-728]
  mov rcx, [rbp-736]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov [r12], rbx
  mov rax, [rbp-736]
  inc rax
  mov r13, rax
  mov [rbp-736], r13
.end_if_24:
  mov rax, [rbp-1192]
  inc rax
  mov r14, rax
  mov rax, r14
  cmp rax, [rbp-752]
  setl al
  movzx rax, al
  mov r15, rax
  mov rax, r15
  cmp rax, 0
  je .end_if_26
.then_25:
  mov rax, [rbp-1192]
  inc rax
  mov rbx, rax
  lea rax, [rbp-472]
  mov rcx, [rbp-736]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov [r12], rbx
  lea rax, [rbp-728]
  mov rcx, [rbp-736]
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov rcx, [rbp-752]
  mov [r13], rcx
  mov rax, [rbp-736]
  inc rax
  mov r14, rax
  mov [rbp-736], r14
.end_if_26:
.end_if_14:
.while_cond_10:
  mov rax, [rbp-736]
  cmp rax, 0
  setg al
  movzx rax, al
  mov r15, rax
  mov rax, r15
  cmp rax, 0
  jne .while_body_11
  jmp .while_end_12
.while_body_11:
  mov rax, [rbp-736]
  dec rax
  mov rbx, rax
  mov [rbp-736], rbx
  lea rax, [rbp-472]
  mov rcx, [rbp-736]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov r13, [r12]
  mov [rbp-744], r13
  lea rax, [rbp-728]
  mov rcx, [rbp-736]
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov r15, [r14]
  mov [rbp-752], r15
  mov rax, [rbp-744]
  cmp rax, [rbp-752]
  setl al
  movzx rax, al
  mov rbx, rax
  mov rax, rbx
  cmp rax, 0
  je .end_if_28
.then_27:
  lea rax, [rbp-80]
  mov rcx, [rbp-752]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov r13, [r12]
  mov [rbp-760], r13
  mov rax, [rbp-744]
  dec rax
  mov r14, rax
  mov [rbp-104], r14
  mov rax, [rbp-744]
  mov [rbp-768], rax
  cmp rax, [rbp-752]
  setl al
  movzx rax, al
  mov r15, rax
  mov rax, r15
  cmp rax, 0
  jne .while_peel_29
  jmp .while_end_32
.while_peel_29:
  lea rax, [rbp-80]
  mov rcx, [rbp-768]
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov r12, [rbx]
  mov rax, r12
  cmp rax, [rbp-760]
  setle al
  movzx rax, al
  mov r13, rax
  mov rax, r13
  cmp rax, 0
  je .end_if_34
.then_33:
  mov rax, [rbp-104]
  inc rax
  mov r14, rax
  mov [rbp-104], r14
  lea rax, [rbp-80]
  mov rcx, [rbp-104]
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rbx, [r15]
  mov [rbp-776], rbx
  lea rax, [rbp-80]
  mov rcx, [rbp-768]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov r13, [r12]
  lea rax, [rbp-80]
  mov rcx, [rbp-104]
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov [r14], r13
  lea rax, [rbp-80]
  mov rcx, [rbp-768]
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rcx, [rbp-776]
  mov [r15], rcx
.end_if_34:
  mov rax, [rbp-768]
  inc rax
  mov rbx, rax
  mov [rbp-768], rbx
.while_cond_30:
  mov rax, [rbp-768]
  cmp rax, [rbp-752]
  setl al
  movzx rax, al
  mov r12, rax
  mov rax, r12
  cmp rax, 0
  jne .while_body_31
  jmp .while_end_32
.while_body_31:
  lea rax, [rbp-80]
  mov rcx, [rbp-768]
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov r14, [r13]
  mov rax, r14
  cmp rax, [rbp-760]
  setle al
  movzx rax, al
  mov r15, rax
  mov rax, r15
  cmp rax, 0
  je .end_if_36
.then_35:
  mov rax, [rbp-104]
  inc rax
  mov rbx, rax
  mov [rbp-104], rbx
  lea rax, [rbp-80]
  mov rcx, [rbp-104]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov r13, [r12]
  mov [rbp-776], r13
  lea rax, [rbp-80]
  mov rcx, [rbp-768]
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov r15, [r14]
  lea rax, [rbp-80]
  mov rcx, [rbp-104]
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov [rbx], r15
  lea rax, [rbp-80]
  mov rcx, [rbp-768]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov rcx, [rbp-776]
  mov [r12], rcx
.end_if_36:
  mov rax, [rbp-768]
  inc rax
  mov r13, rax
  mov [rbp-768], r13
  jmp .while_cond_30
.while_end_32:
  mov rax, [rbp-104]
  inc rax
  mov r14, rax
  mov [rbp-1192], r14
  lea rax, [rbp-80]
  mov rcx, [rbp-1192]
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rbx, [r15]
  mov [rbp-784], rbx
  lea rax, [rbp-80]
  mov rcx, [rbp-752]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov r13, [r12]
  lea rax, [rbp-80]
  mov rcx, [rbp-1192]
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov [r14], r13
  lea rax, [rbp-80]
  mov rcx, [rbp-752]
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov rcx, [rbp-784]
  mov [r15], rcx
  mov rax, [rbp-1192]
  dec rax
  mov rbx, rax
  mov rax, [rbp-744]
  cmp rax, rbx
  setl al
  movzx rax, al
  mov r12, rax
  mov rax, r12
  cmp rax, 0
  je .end_if_38
.then_37:
  lea rax, [rbp-472]
  mov rcx, [rbp-736]
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov rcx, [rbp-744]
  mov [r13], rcx
  mov rax, [rbp-1192]
  dec rax
  mov r14, rax
  lea rax, [rbp-728]
  mov rcx, [rbp-736]
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov [r15], r14
  mov rax, [rbp-736]
  inc rax
  mov rbx, rax
  mov [rbp-736], rbx
.end_if_38:
  mov rax, [rbp-1192]
  inc rax
  mov r12, rax
  mov rax, r12
  cmp rax, [rbp-752]
  setl al
  movzx rax, al
  mov r13, rax
  mov rax, r13
  cmp rax, 0
  je .end_if_40
.then_39:
  mov rax, [rbp-1192]
  inc rax
  mov r14, rax
  lea rax, [rbp-472]
  mov rcx, [rbp-736]
  shl rcx, 3
  add rax, rcx
  mov r15, rax
  mov [r15], r14
  lea rax, [rbp-728]
  mov rcx, [rbp-736]
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov rcx, [rbp-752]
  mov [rbx], rcx
  mov rax, [rbp-736]
  inc rax
  mov r12, rax
  mov [rbp-736], r12
.end_if_40:
.end_if_28:
  jmp .while_cond_10
.while_end_12:
  mov rdi, str_41
  mov eax, 0
  call printf
  xor eax, eax
  mov [rbp-104], rax
.for_cond_42:
  cmp rax, 10
  setl al
  movzx rax, al
  mov r13, rax
  mov rax, r13
  cmp rax, 0
  jne .for_body_43
  jmp .for_end_45
.for_body_43:
  lea rax, [rbp-80]
  mov rcx, [rbp-104]
  shl rcx, 3
  add rax, rcx
  mov r14, rax
  mov r15, [r14]
  mov rdi, str_46
  mov rsi, r15
  mov eax, 0
  call printf
.for_update_44:
  mov rax, [rbp-104]
  inc rax
  mov rbx, rax
  mov [rbp-104], rbx
  jmp .for_cond_42
.for_end_45:
  mov rdi, str_47
  mov eax, 0
  call printf
  mov rdi, str_48
  mov eax, 0
  call printf
  xor eax, eax
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret
.main_epilogue_fallback:
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall

section .data
str_1: db `Quick Sort\n`, 0
str_2: db `Before: `, 0
str_7: db `%d `, 0
str_8: db `\n`, 0
str_41: db `After:  `, 0
str_46: db `%d `, 0
str_47: db `\n`, 0
str_48: db `Quick sort complete!\n`, 0