; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global is_even
is_even:
  push rbp
  mov rbp, rsp
  sub rsp, 16
  push rbx
  push r12
  mov [rbp-8], rdi
.func_is_even:
  mov rax, [rbp-8]
  cqo
  mov rcx, 2
  idiv rcx
  mov rbx, rdx
  mov rax, rbx
  cmp rax, 0
  sete al
  movzx rax, al
  mov r12, rax
  mov rax, r12
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret
.is_even_epilogue_fallback:
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 256
  push rbx
  push r12
  push r13
  push r14
  push r15
.func_main:
  mov rdi, str_1
  mov eax, 0
  call printf
  mov [rbp-8], rax
.for_cond_2:
  mov rax, [rbp-120]
  cmp rax, 10
  setl al
  movzx rax, al
  mov rbx, rax
  mov rax, rbx
  cmp rax, 0
  jne .for_body_3
  jmp .for_end_5
.for_body_3:
  mov rax, [rbp-120]
  imul rax, 10
  mov r12, rax
  lea rax, [rbp-88]
  mov rcx, [rbp-120]
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov [r13], r12
.for_update_4:
  mov rax, [rbp-120]
  inc rax
  mov r14, rax
  mov [rbp-120], r14
  jmp .for_cond_2
.for_end_5:
.while_cond_6:
  mov rax, [rbp-168]
  cmp rax, 10
  setl al
  movzx rax, al
  mov r15, rax
  mov rax, r15
  cmp rax, 0
  jne .while_body_7
  jmp .while_end_8
.while_body_7:
  lea rax, [rbp-88]
  mov rcx, [rbp-168]
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov r12, [rbx]
  mov [rbp-176], r12
  mov rax, [rbp-176]
  cqo
  mov rcx, 10
  idiv rcx
  mov r13, rax
  mov rdi, r13
  call is_even
  cmp rax, 0
  je .else_11
.else_11:
  mov rdi, str_13
  mov rsi, [rbp-176]
  mov eax, 0
  call printf
.end_if_10:
  mov rax, [rbp-168]
  inc rax
  mov rbx, rax
  mov [rbp-168], rbx
  jmp .while_cond_6
.while_end_8:
  mov rdi, str_14
  mov rsi, [rbp-160]
  mov eax, 0
  call printf
  mov rdi, 16
  call malloc
  mov [rbp-200], rax
  mov rdi, str_15
  mov rsi, [rbp-200]
  mov eax, 0
  call printf
  mov rdi, [rbp-200]
  call free
  mov rdi, str_16
  mov eax, 0
  call printf
  mov rax, [rbp-160]
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret
.main_epilogue_fallback:
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall

section .data
str_1: db `Starting combined Sprint 6 & 7 test...\n`, 0
str_12: db `Added even index element: %d\n`, 0
str_13: db `Skipped odd index element: %d\n`, 0
str_14: db `Final sum of even index elements: %d\n`, 0
str_15: db `Allocated 16 bytes at address: %d\n`, 0
str_16: db `Test completed successfully!\n`, 0