; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global is_even
is_even:
  push rbp
  mov rbp, rsp
  sub rsp, 16
  push rbx
  push r12
  mov [rbp-8], rdi
.func_is_even:
  mov rax, [rbp-8]
  and rax, 1
  mov r12, rax
  mov rax, r12
  cmp rax, 0
  sete al
  movzx rax, al
  mov rbx, rax
  mov rax, rbx
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret
.is_even_epilogue_fallback:
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 416
  push rbx
  push r12
  push r13
  push r14
  push r15
.func_main:
  mov rdi, str_1
  mov eax, 0
  call printf
  mov [rbp-8], rax
  xor eax, eax
  mov [rbp-96], rax
.for_cond_2:
  cmp rax, 10
  setl al
  movzx rax, al
  mov rbx, rax
  mov rax, rbx
  cmp rax, 0
  jne .for_body_3
  jmp .for_end_5
.for_body_3:
  mov rax, [rbp-96]
  imul rax, 10
  mov r12, rax
  lea rax, [rbp-88]
  mov rcx, [rbp-96]
  shl rcx, 3
  add rax, rcx
  mov r13, rax
  mov [r13], r12
.for_update_4:
  mov rax, [rbp-96]
  inc rax
  mov r14, rax
  mov [rbp-96], r14
  jmp .for_cond_2
.for_end_5:
  xor eax, eax
  mov [rbp-128], rax
  xor eax, eax
  mov [rbp-136], rax
  cmp rax, 10
  setl al
  movzx rax, al
  mov r15, rax
  mov rax, r15
  cmp rax, 0
  jne .while_peel_6
  jmp .while_end_9
.while_peel_6:
  lea rax, [rbp-88]
  mov rcx, [rbp-136]
  shl rcx, 3
  add rax, rcx
  mov rbx, rax
  mov r12, [rbx]
  mov [rbp-144], r12
  mov rax, [rbp-144]
  cqo
  mov rcx, 10
  idiv rcx
  mov r13, rax
  mov rdi, r13
  call is_even
  cmp rax, 0
  je .else_12
.then_10:
  mov rax, [rbp-128]
  add rax, qword [rbp-144]
  mov r14, rax
  mov [rbp-128], r14
  mov rdi, str_13
  mov rsi, [rbp-144]
  mov eax, 0
  call printf
  jmp .end_if_11
.else_12:
  mov rdi, str_14
  mov rsi, [rbp-144]
  mov eax, 0
  call printf
.end_if_11:
  mov rax, [rbp-136]
  inc rax
  mov r15, rax
  mov [rbp-136], r15
.while_cond_7:
  mov rax, [rbp-136]
  cmp rax, 10
  setl al
  movzx rax, al
  mov rbx, rax
  mov rax, rbx
  cmp rax, 0
  jne .while_body_8
  jmp .while_end_9
.while_body_8:
  lea rax, [rbp-88]
  mov rcx, [rbp-136]
  shl rcx, 3
  add rax, rcx
  mov r12, rax
  mov r13, [r12]
  mov [rbp-144], r13
  mov rax, [rbp-144]
  cqo
  mov rcx, 10
  idiv rcx
  mov r14, rax
  mov rdi, r14
  call is_even
  cmp rax, 0
  je .else_17
.then_15:
  mov rax, [rbp-128]
  add rax, qword [rbp-144]
  mov r15, rax
  mov [rbp-128], r15
  mov rdi, str_18
  mov rsi, [rbp-144]
  mov eax, 0
  call printf
  jmp .end_if_16
.else_17:
  mov rdi, str_19
  mov rsi, [rbp-144]
  mov eax, 0
  call printf
.end_if_16:
  mov rax, [rbp-136]
  inc rax
  mov r15, rax
  mov [rbp-136], r15
  jmp .while_cond_7
.while_end_9:
  mov rdi, str_20
  mov rsi, [rbp-128]
  mov eax, 0
  call printf
  mov rdi, 16
  call malloc
  mov [rbp-344], rax
  mov rdi, str_21
  mov rsi, [rbp-344]
  mov eax, 0
  call printf
  mov rdi, [rbp-344]
  call free
  mov rdi, str_22
  mov eax, 0
  call printf
  mov rax, [rbp-128]
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret
.main_epilogue_fallback:
  pop r15
  pop r14
  pop r13
  pop r12
  pop rbx
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall

section .data
str_1: db `Starting combined Sprint 6 & 7 test...\n`, 0
str_13: db `Added even index element: %d\n`, 0
str_14: db `Skipped odd index element: %d\n`, 0
str_18: db `Added even index element: %d\n`, 0
str_19: db `Skipped odd index element: %d\n`, 0
str_20: db `Final sum of even index elements: %d\n`, 0
str_21: db `Allocated 16 bytes at address: %d\n`, 0
str_22: db `Test completed successfully!\n`, 0