; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global is_even
is_even:
  push rbp
  mov rbp, rsp
  sub rsp, 32
  mov [rbp-8], rdi
.func_is_even:
  mov rax, [rbp-8]
  cqo
  mov rcx, 2
  idiv rcx
  mov [rbp-16], rdx
  mov rax, [rbp-16]
  cmp rax, 0
  sete al
  movzx rax, al
  mov rsp, rbp
  pop rbp
  ret
.is_even_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 432
.func_main:
  mov rdi, str_1
  mov eax, 0
  call printf
  mov [rbp-8], rax
.for_cond_2:
  xor eax, eax
  mov [rbp-120], rax
  cmp rax, 10
  setl al
  movzx rax, al
  cmp rax, 0
  jne .for_body_3
  jmp .for_end_5
.for_body_3:
  mov rax, [rbp-120]
  imul rax, 10
  mov [rbp-136], rax
  lea rax, [rbp-88]
  mov rcx, [rbp-120]
  shl rcx, 3
  add rax, rcx
  mov rcx, [rbp-136]
  mov [rax], rcx
.for_update_4:
  mov rax, [rbp-120]
  inc rax
  mov [rbp-120], rax
  jmp .for_cond_2
.for_end_5:
.while_cond_6:
  xor eax, eax
  mov [rbp-192], rax
  xor eax, eax
  mov [rbp-200], rax
  cmp rax, 10
  setl al
  movzx rax, al
  cmp rax, 0
  jne .while_body_7
  jmp .while_end_8
.while_body_7:
  lea rax, [rbp-88]
  mov rcx, [rbp-200]
  shl rcx, 3
  add rax, rcx
  mov rcx, [rax]
  mov [rbp-224], rcx
  mov rax, [rbp-224]
  mov [rbp-232], rax
  cqo
  mov rcx, 10
  idiv rcx
  mov [rbp-240], rax
  mov rdi, [rbp-240]
  call is_even
  cmp rax, 0
  je .else_11
  jmp .then_9
.else_11:
  mov rdi, str_13
  mov rsi, [rbp-232]
  mov eax, 0
  call printf
  jmp .end_if_10
.then_9:
  mov rax, [rbp-192]
  add rax, qword [rbp-232]
  mov [rbp-192], rax
  mov rdi, str_12
  mov rsi, [rbp-232]
  mov eax, 0
  call printf
.end_if_10:
  mov rax, [rbp-200]
  inc rax
  mov [rbp-200], rax
  jmp .while_cond_6
.while_end_8:
  mov rdi, str_14
  mov rsi, [rbp-192]
  mov eax, 0
  call printf
  mov rdi, 16
  call malloc
  mov [rbp-376], rax
  mov rdi, str_15
  mov rsi, [rbp-376]
  mov eax, 0
  call printf
  mov rdi, [rbp-376]
  call free
  mov rdi, str_16
  mov eax, 0
  call printf
  mov rax, [rbp-192]
  mov rsp, rbp
  pop rbp
  ret
.main_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall

section .data
str_1: db `Starting combined Sprint 6 & 7 test...\n`, 0
str_12: db `Added even index element: %d\n`, 0
str_13: db `Skipped odd index element: %d\n`, 0
str_14: db `Final sum of even index elements: %d\n`, 0
str_15: db `Allocated 16 bytes at address: %d\n`, 0
str_16: db `Test completed successfully!\n`, 0