; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 160
.func_main:
  lea rax, [rbp-40]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov [rbp-48], rax
  mov rcx, 10
  mov [rax], rcx
  lea rax, [rbp-40]
  mov rcx, 1
  shl rcx, 3
  add rax, rcx
  mov [rbp-56], rax
  mov rcx, 20
  mov [rax], rcx
  lea rax, [rbp-40]
  mov rcx, 2
  shl rcx, 3
  add rax, rcx
  mov [rbp-64], rax
  mov rcx, 30
  mov [rax], rcx
  lea rax, [rbp-40]
  mov rcx, 3
  shl rcx, 3
  add rax, rcx
  mov [rbp-72], rax
  mov rcx, 40
  mov [rax], rcx
  lea rax, [rbp-40]
  mov rcx, 4
  shl rcx, 3
  add rax, rcx
  mov [rbp-80], rax
  mov rcx, 50
  mov [rax], rcx
  xor eax, eax
  mov [rbp-88], rax
  xor eax, eax
  mov [rbp-96], rax
  jmp .for_cond_1
.for_cond_1:
  mov rax, [rbp-96]
  cmp rax, 5
  setl al
  movzx rax, al
  mov [rbp-104], rax
  cmp rax, 0
  jne .for_body_2
  jmp .for_end_4
.for_end_4:
  mov rdi, str_5
  mov rsi, [rbp-88]
  mov eax, 0
  call printf
  mov [rbp-112], rax
  mov rax, [rbp-88]
  mov rsp, rbp
  pop rbp
  ret
.for_body_2:
  lea rax, [rbp-40]
  mov rcx, [rbp-96]
  shl rcx, 3
  add rax, rcx
  mov [rbp-120], rax
  mov rcx, [rax]
  mov [rbp-128], rcx
  mov rax, [rbp-88]
  add rax, qword [rbp-128]
  mov [rbp-136], rax
  mov [rbp-88], rax
  jmp .for_update_3
.for_update_3:
  mov rax, [rbp-96]
  inc rax
  mov [rbp-144], rax
  mov [rbp-96], rax
  jmp .for_cond_1
.main_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall

section .data
str_5: db `Total sum of array: %d\n`, 0