; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 208
.func_main:
  lea rax, [rbp-40]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov [rbp-48], rax
  mov rcx, 10
  mov [rax], rcx
  lea rax, [rbp-40]
  mov rcx, 1
  shl rcx, 3
  add rax, rcx
  mov [rbp-72], rax
  mov rcx, 20
  mov [rax], rcx
  lea rax, [rbp-40]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov [rbp-96], rax
  mov rcx, [rax]
  mov [rbp-104], rcx
  lea rax, [rbp-40]
  mov rcx, 1
  shl rcx, 3
  add rax, rcx
  mov [rbp-112], rax
  mov rcx, [rax]
  mov [rbp-120], rcx
  mov rax, [rbp-104]
  add rax, qword [rbp-120]
  mov [rbp-128], rax
  mov [rbp-136], rax
  lea rax, [rbp-160]
  mov rcx, 0
  shl rcx, 3
  add rax, rcx
  mov [rbp-168], rax
  mov rcx, 1
  mov [rax], rcx
  lea rax, [rbp-160]
  mov rcx, 1
  shl rcx, 3
  add rax, rcx
  mov [rbp-176], rax
  mov rcx, 2
  mov [rax], rcx
  lea rax, [rbp-160]
  mov rcx, 2
  shl rcx, 3
  add rax, rcx
  mov [rbp-192], rax
  mov rcx, 3
  mov [rax], rcx
.main_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall