use crate::ir::ir_instructions::{IRInstruction, Operand};
use crate::ir::basic_block::BasicBlock;
use crate::ir::ir_generator::FunctionMetadata;
use crate::codegen::{abi, label_manager::LabelManager, expression_generator::ExpressionGenerator, control_flow_generator::ControlFlowGenerator, stack_frame::StackFrame, optimizer::PeepholeOptimizer};
use std::collections::HashMap;

pub struct X86Generator {
    blocks: HashMap<String, BasicBlock>,
    functions: Vec<FunctionMetadata>,
    output: String,
    stack_frame: StackFrame,
    params: Vec<Operand>,
}

impl X86Generator {
    pub fn new(blocks: HashMap<String, BasicBlock>, functions: Vec<FunctionMetadata>) -> Self {
        Self {
            blocks,
            functions,
            output: String::new(),
            stack_frame: StackFrame::new(),
            params: Vec::new(),
        }
    }

    pub fn generate(&mut self) -> String {
        self.output.push_str("; Generated by MiniCompiler\n");
        self.output.push_str("bits 64\n\n");
        
        self.output.push_str("extern print_int\n");
        self.output.push_str("extern read_int\n");
        self.output.push_str("extern exit\n\n");

        self.output.push_str("section .text\n");

        let functions = self.functions.clone();
        for func in &functions {
            self.generate_function(func);
        }

        self.output.push_str("\nglobal _start\n");
        self.output.push_str("_start:\n");
        self.output.push_str("  call main\n");
        self.output.push_str("  mov rdi, rax\n");
        self.output.push_str("  mov rax, 60\n");
        self.output.push_str("  syscall\n");

        PeepholeOptimizer::optimize(self.output.clone())
    }

    fn generate_function(&mut self, func: &FunctionMetadata) {
        let entry_label = format!("func_{}", func.name);
        self.output.push_str(&format!("\nglobal {}\n", func.name));
        self.output.push_str(&format!("{}:\n", func.name));

        self.stack_frame.reset();

        let reachable = self.get_reachable_blocks(&entry_label);
        
        for p_name in &func.parameters {
            let op = Operand::Var { name: p_name.clone(), version: 0 };
            self.stack_frame.get_offset(&op);
        }

        for blk_label in &reachable {
            let instructions = self.blocks.get(blk_label).map(|b| b.instructions.clone()).unwrap_or_default();
            for inst in instructions {
                self.track_operands(&inst);
            }
        }

        self.output.push_str("  push rbp\n");
        self.output.push_str("  mov rbp, rsp\n");

        let stack_size = self.stack_frame.aligned_size();
        if stack_size > 0 {
            self.output.push_str(&format!("  sub rsp, {}\n", stack_size));
        }

        for (i, p_name) in func.parameters.iter().enumerate() {
            if i < 6 {
                let reg = abi::INTEGER_ARG_REGISTERS[i];
                let op = Operand::Var { name: p_name.clone(), version: 0 };
                let sf = &mut self.stack_frame;
                self.output.push_str(&ExpressionGenerator::store_operand(&op, reg, &mut |o| sf.get_offset(o)));
            }
        }

        for blk_label in reachable {
            self.generate_block(&blk_label);
        }
    }

    fn track_operands(&mut self, inst: &IRInstruction) {
        match inst {
            IRInstruction::Add { result, .. } | IRInstruction::Sub { result, .. } |
            IRInstruction::Mul { result, .. } | IRInstruction::Div { result, .. } |
            IRInstruction::And { result, .. } | IRInstruction::Or { result, .. } |
            IRInstruction::Xor { result, .. } | IRInstruction::Not { result, .. } |
            IRInstruction::Equal { result, .. } | IRInstruction::NotEqual { result, .. } |
            IRInstruction::Less { result, .. } | IRInstruction::LessEqual { result, .. } |
            IRInstruction::Greater { result, .. } | IRInstruction::GreaterEqual { result, .. } |
            IRInstruction::Neg { result, .. } | IRInstruction::Move { result, .. } |
            IRInstruction::Call { result: Some(result), .. } | IRInstruction::Phi { result, .. } => {
                self.stack_frame.get_offset(result);
            }
            _ => {}
        }
    }

    fn get_reachable_blocks(&self, start: &String) -> Vec<String> {
        let mut visited = Vec::new();
        let mut stack = vec![start.clone()];
        while let Some(label) = stack.pop() {
            if visited.contains(&label) { continue; }
            visited.push(label.clone());
            if let Some(blk) = self.blocks.get(&label) {
                for succ in &blk.successors {
                    if !succ.starts_with("func_") {
                        stack.push(succ.clone());
                    }
                }
            }
        }
        if let Some(pos) = visited.iter().position(|l| l == start) { visited.swap(0, pos); }
        visited
    }

    fn generate_block(&mut self, label: &String) {
        self.output.push_str(&format!("{}:\n", LabelManager::block_label(label)));
        let insts = self.blocks.get(label).unwrap().instructions.clone();
        for inst in insts {
            self.generate_instruction(&inst);
        }
    }

    fn generate_instruction(&mut self, inst: &IRInstruction) {
        let sf = &mut self.stack_frame;
        // Use a local scope to ensure offset_provider doesn't outlive operand_to_str calls
        match inst {
            IRInstruction::Add { result, left, right } => {
                let right_str = Self::static_operand_to_str(right, sf);
                self.output.push_str(&ExpressionGenerator::load_operand("rax", left, &mut |o| sf.get_offset(o)));
                self.output.push_str(&format!("  add rax, {}\n", right_str));
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Sub { result, left, right } => {
                let right_str = Self::static_operand_to_str(right, sf);
                self.output.push_str(&ExpressionGenerator::load_operand("rax", left, &mut |o| sf.get_offset(o)));
                self.output.push_str(&format!("  sub rax, {}\n", right_str));
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Mul { result, left, right } => {
                let right_str = Self::static_operand_to_str(right, sf);
                self.output.push_str(&ExpressionGenerator::load_operand("rax", left, &mut |o| sf.get_offset(o)));
                self.output.push_str(&format!("  imul rax, {}\n", right_str));
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Div { result, left, right } => {
                let right_str = Self::static_operand_to_str(right, sf);
                self.output.push_str(&ExpressionGenerator::load_operand("rax", left, &mut |o| sf.get_offset(o)));
                self.output.push_str("  cqo\n");
                self.output.push_str(&format!("  idiv {}\n", right_str));
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Move { result, source } => {
                self.output.push_str(&ExpressionGenerator::load_operand("rax", source, &mut |o| sf.get_offset(o)));
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Return { value } => {
                if let Some(v) = value {
                    self.output.push_str(&ExpressionGenerator::load_operand("rax", v, &mut |o| sf.get_offset(o)));
                }
                self.output.push_str("  mov rsp, rbp\n  pop rbp\n  ret\n");
            }
            IRInstruction::Jump { label } => {
                self.output.push_str(&ControlFlowGenerator::generate_jump(label));
            }
            IRInstruction::JumpIfTrue { condition, label } => {
                self.output.push_str(&ExpressionGenerator::load_operand("rax", condition, &mut |o| sf.get_offset(o)));
                self.output.push_str(&ControlFlowGenerator::generate_jump_if("rax", label, true));
            }
            IRInstruction::JumpIfFalse { condition, label } => {
                self.output.push_str(&ExpressionGenerator::load_operand("rax", condition, &mut |o| sf.get_offset(o)));
                self.output.push_str(&ControlFlowGenerator::generate_jump_if("rax", label, false));
            }
            IRInstruction::Param { value } => { self.params.push(value.clone()); }
            IRInstruction::Call { result, callee, num_args } => {
                let start_idx = self.params.len().saturating_sub(*num_args);
                for i in 0..*num_args {
                    let arg = self.params[start_idx + i].clone();
                    if i < 6 {
                        let reg = abi::INTEGER_ARG_REGISTERS[i];
                        self.output.push_str(&ExpressionGenerator::load_operand(reg, &arg, &mut |o| sf.get_offset(o)));
                    }
                }
                self.output.push_str(&format!("  call {}\n", callee));
                if let Some(r) = result {
                    self.output.push_str(&ExpressionGenerator::store_operand(r, "rax", &mut |o| sf.get_offset(o)));
                }
                self.params.truncate(start_idx);
            }
            IRInstruction::Equal { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::generate_comparison("sete", result, left, right, &mut |o| sf.get_offset(o)));
            }
            IRInstruction::NotEqual { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::generate_comparison("setne", result, left, right, &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Less { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::generate_comparison("setl", result, left, right, &mut |o| sf.get_offset(o)));
            }
            IRInstruction::LessEqual { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::generate_comparison("setle", result, left, right, &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Greater { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::generate_comparison("setg", result, left, right, &mut |o| sf.get_offset(o)));
            }
            IRInstruction::GreaterEqual { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::generate_comparison("setge", result, left, right, &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Neg { result, operand } => {
                self.output.push_str(&ExpressionGenerator::load_operand("rax", operand, &mut |o| sf.get_offset(o)));
                self.output.push_str("  neg rax\n");
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Not { result, operand } => {
                self.output.push_str(&ExpressionGenerator::load_operand("rax", operand, &mut |o| sf.get_offset(o)));
                self.output.push_str("  xor rax, 1\n");
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            _ => { self.output.push_str(&format!("  ; Unimplemented: {}\n", inst)); }
        }
    }

    fn static_operand_to_str(op: &Operand, sf: &mut StackFrame) -> String {
        match op {
            Operand::Literal { value } => value.clone(),
            _ => {
                let offset = sf.get_offset(op);
                format!("qword [rbp{}]", if offset >= 0 { format!("+{}", offset) } else { offset.to_string() })
            }
        }
    }
}
