use crate::ir::ir_instructions::{IRInstruction, Operand};
use crate::ir::basic_block::BasicBlock;
use crate::ir::ir_generator::FunctionMetadata;
use crate::codegen::{abi, label_manager::LabelManager, expression_generator::ExpressionGenerator, control_flow_generator::ControlFlowGenerator, stack_frame::StackFrame, optimizer::PeepholeOptimizer};
use std::collections::HashMap;

pub struct X86Generator {
    blocks: HashMap<String, BasicBlock>,
    functions: Vec<FunctionMetadata>,
    output: String,
    stack_frame: StackFrame,
    params: Vec<Operand>,
    strings: Vec<(String, String)>,
}

impl X86Generator {
    pub fn new(blocks: HashMap<String, BasicBlock>, functions: Vec<FunctionMetadata>, strings: Vec<(String, String)>) -> Self {
        Self {
            blocks,
            functions,
            output: String::new(),
            stack_frame: StackFrame::new(),
            params: Vec::new(),
            strings,
        }
    }

    pub fn generate(&mut self) -> String {
        self.output.push_str("; Generated by MiniCompiler\n");
        self.output.push_str("bits 64\n\n");
        
        self.output.push_str("extern print_int\n");
        self.output.push_str("extern read_int\n");
        self.output.push_str("extern printf\n");
        self.output.push_str("extern scanf\n");
        self.output.push_str("extern malloc\n");
        self.output.push_str("extern free\n");
        self.output.push_str("extern exit\n\n");

        self.output.push_str("section .text\n");

        let functions = self.functions.clone();
        for func in &functions {
            self.generate_function(func);
        }

        self.output.push_str("\nglobal _start\n");
        self.output.push_str("_start:\n");
        self.output.push_str("  call main\n");
        self.output.push_str("  mov rdi, rax\n");
        self.output.push_str("  mov rax, 60\n");
        self.output.push_str("  syscall\n");

        if !self.strings.is_empty() {
            self.output.push_str("\nsection .data\n");
            for (label, val) in &self.strings {
                self.output.push_str(&format!("{}: db {}, 0\n", label, val));
            }
        }

        PeepholeOptimizer::optimize(self.output.clone())
    }

    fn generate_function(&mut self, func: &FunctionMetadata) {
        let entry_label = format!("func_{}", func.name);
        self.output.push_str(&format!("\nglobal {}\n", func.name));
        self.output.push_str(&format!("{}:\n", func.name));

        self.stack_frame.reset();

        let reachable = self.get_reachable_blocks(&entry_label);
        
        for p_name in &func.parameters {
            let op = Operand::Var { name: p_name.clone(), version: 0 };
            self.stack_frame.get_offset(&op);
        }

        for blk_label in &reachable {
            let instructions = self.blocks.get(blk_label).map(|b| b.instructions.clone()).unwrap_or_default();
            for inst in instructions {
                self.track_operands(&inst);
            }
        }

        self.output.push_str("  push rbp\n");
        self.output.push_str("  mov rbp, rsp\n");

        let stack_size = self.stack_frame.aligned_size();
        if stack_size > 0 {
            self.output.push_str(&format!("  sub rsp, {}\n", stack_size));
        }

        for (i, p_name) in func.parameters.iter().enumerate() {
            if i < 6 {
                let reg = abi::INTEGER_ARG_REGISTERS[i];
                let op = Operand::Var { name: p_name.clone(), version: 0 };
                let sf = &mut self.stack_frame;
                self.output.push_str(&ExpressionGenerator::store_operand(&op, reg, &mut |o| sf.get_offset(o)));
            }
        }

        for blk_label in reachable {
            self.generate_block(&blk_label);
        }

        // Гарантируем наличие эпилога и возврата из функции (особенно для void функций или main)
        self.output.push_str(&format!(".{}_epilogue_fallback:\n", func.name));
        self.output.push_str("  mov rsp, rbp\n");
        self.output.push_str("  pop rbp\n");
        self.output.push_str("  ret\n");
    }

    fn track_operands(&mut self, inst: &IRInstruction) {
        let sf = &mut self.stack_frame;
        let mut track = |op: &Operand| {
            if let Operand::Var { .. } | Operand::Temp { .. } = op {
                sf.get_offset(op);
            }
        };

        match inst {
            IRInstruction::Add { result, left, right } | IRInstruction::Sub { result, left, right } |
            IRInstruction::Mul { result, left, right } | IRInstruction::Div { result, left, right } |
            IRInstruction::Mod { result, left, right } |
            IRInstruction::And { result, left, right } | IRInstruction::Or { result, left, right } |
            IRInstruction::Xor { result, left, right } |
            IRInstruction::Equal { result, left, right } | IRInstruction::NotEqual { result, left, right } |
            IRInstruction::Less { result, left, right } | IRInstruction::LessEqual { result, left, right } |
            IRInstruction::Greater { result, left, right } | IRInstruction::GreaterEqual { result, left, right } => {
                track(result);
                track(left);
                track(right);
            }
            IRInstruction::Move { result, source: operand } => {
                track(result);
                track(operand);
            }
            IRInstruction::Not { result, operand } | IRInstruction::Neg { result, operand } => {
                track(result);
                track(operand);
            }
            IRInstruction::Call { result, num_args, .. } => {
                if let Some(r) = result { track(r); }
            }
            IRInstruction::Phi { result, sources } => {
                track(result);
                for (op, _) in sources { track(op); }
            }
            IRInstruction::Alloca { result, size } => {
                sf.allocate_array(result, *size);
            }
            IRInstruction::Load { result, address } => {
                track(result);
                track(address);
            }
            IRInstruction::Store { address, source } => {
                track(address);
                track(source);
            }
            IRInstruction::GetElementPtr { result, base, offset } => {
                track(result);
                track(base);
                track(offset);
            }
            IRInstruction::JumpIfTrue { condition, .. } | IRInstruction::JumpIfFalse { condition, .. } => {
                track(condition);
            }
            IRInstruction::Return { value: Some(op) } | IRInstruction::Param { value: op } => {
                track(op);
            }
            IRInstruction::Return { value: None } | IRInstruction::Jump { .. } => {}
        }
    }

    /// Returns blocks in Reverse Post-Order (RPO) — a stable, correct linear order
    /// for code emission. By iterating successors in reverse order, we ensure that
    /// leaf blocks (like for_end or function ends) are visited first in DFS,
    /// placed early in post-order, and thus end up LAST in the final RPO.
    /// This eliminates fall-through bugs caused by empty blocks.
    fn get_reachable_blocks(&self, start: &String) -> Vec<String> {
        let mut post_order: Vec<String> = Vec::new();
        let mut visited: std::collections::HashSet<String> = std::collections::HashSet::new();

        fn dfs(
            node: &str,
            blocks: &std::collections::HashMap<String, BasicBlock>,
            visited: &mut std::collections::HashSet<String>,
            post_order: &mut Vec<String>,
        ) {
            if !visited.insert(node.to_string()) { return; }
            if let Some(blk) = blocks.get(node) {
                // Visit successors in REVERSE order.
                // This forces 'end' blocks to be pushed to post_order early,
                // meaning they will appear late in the RPO list.
                for succ in blk.successors.iter().rev() {
                    if !succ.starts_with("func_") {
                        dfs(succ, blocks, visited, post_order);
                    }
                }
            }
            post_order.push(node.to_string());
        }

        dfs(start, &self.blocks, &mut visited, &mut post_order);

        post_order.reverse();
        post_order
    }

    fn generate_block(&mut self, label: &String) {
        self.output.push_str(&format!("{}:\n", LabelManager::block_label(label)));
        let insts = self.blocks.get(label).unwrap().instructions.clone();
        for inst in insts {
            self.generate_instruction(&inst);
        }
    }

    fn generate_instruction(&mut self, inst: &IRInstruction) {
        let sf = &mut self.stack_frame;
        // Use a local scope to ensure offset_provider doesn't outlive operand_to_str calls
        match inst {
            IRInstruction::Add { result, left, right } => {
                let right_str = Self::static_operand_to_str(right, sf);
                self.output.push_str(&ExpressionGenerator::load_operand("rax", left, &mut |o| sf.get_offset(o)));
                self.output.push_str(&format!("  add rax, {}\n", right_str));
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Sub { result, left, right } => {
                let right_str = Self::static_operand_to_str(right, sf);
                self.output.push_str(&ExpressionGenerator::load_operand("rax", left, &mut |o| sf.get_offset(o)));
                self.output.push_str(&format!("  sub rax, {}\n", right_str));
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Mul { result, left, right } => {
                let right_str = Self::static_operand_to_str(right, sf);
                self.output.push_str(&ExpressionGenerator::load_operand("rax", left, &mut |o| sf.get_offset(o)));
                self.output.push_str(&format!("  imul rax, {}\n", right_str));
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Div { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::load_operand("rax", left, &mut |o| sf.get_offset(o)));
                self.output.push_str("  cqo\n");
                // idiv does NOT accept immediate operands — always load divisor into rcx
                match right {
                    Operand::Literal { value } => {
                        self.output.push_str(&format!("  mov rcx, {}\n", value));
                        self.output.push_str("  idiv rcx\n");
                    }
                    _ => {
                        let right_str = Self::static_operand_to_str(right, sf);
                        self.output.push_str(&format!("  idiv {}\n", right_str));
                    }
                }
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Mod { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::load_operand("rax", left, &mut |o| sf.get_offset(o)));
                self.output.push_str("  cqo\n");
                // idiv does NOT accept immediate operands — always load divisor into rcx
                match right {
                    Operand::Literal { value } => {
                        self.output.push_str(&format!("  mov rcx, {}\n", value));
                        self.output.push_str("  idiv rcx\n");
                    }
                    _ => {
                        let right_str = Self::static_operand_to_str(right, sf);
                        self.output.push_str(&format!("  idiv {}\n", right_str));
                    }
                }
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rdx", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::And { result, left, right } => {
                let right_str = Self::static_operand_to_str(right, sf);
                self.output.push_str(&ExpressionGenerator::load_operand("rax", left, &mut |o| sf.get_offset(o)));
                self.output.push_str(&format!("  and rax, {}\n", right_str));
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Or { result, left, right } => {
                let right_str = Self::static_operand_to_str(right, sf);
                self.output.push_str(&ExpressionGenerator::load_operand("rax", left, &mut |o| sf.get_offset(o)));
                self.output.push_str(&format!("  or rax, {}\n", right_str));
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Xor { result, left, right } => {
                let right_str = Self::static_operand_to_str(right, sf);
                self.output.push_str(&ExpressionGenerator::load_operand("rax", left, &mut |o| sf.get_offset(o)));
                self.output.push_str(&format!("  xor rax, {}\n", right_str));
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Move { result, source } => {
                if sf.get_offset(result) == sf.get_offset(source) { return; }
                self.output.push_str(&ExpressionGenerator::load_operand("rax", source, &mut |o| sf.get_offset(o)));
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Return { value } => {
                if let Some(v) = value {
                    self.output.push_str(&ExpressionGenerator::load_operand("rax", v, &mut |o| sf.get_offset(o)));
                }
                self.output.push_str("  mov rsp, rbp\n  pop rbp\n  ret\n");
            }
            IRInstruction::Jump { label } => {
                self.output.push_str(&ControlFlowGenerator::generate_jump(label));
            }
            IRInstruction::JumpIfTrue { condition, label } => {
                self.output.push_str(&ExpressionGenerator::load_operand("rax", condition, &mut |o| sf.get_offset(o)));
                self.output.push_str(&ControlFlowGenerator::generate_jump_if("rax", label, true));
            }
            IRInstruction::JumpIfFalse { condition, label } => {
                self.output.push_str(&ExpressionGenerator::load_operand("rax", condition, &mut |o| sf.get_offset(o)));
                self.output.push_str(&ControlFlowGenerator::generate_jump_if("rax", label, false));
            }
            IRInstruction::Param { value } => { self.params.push(value.clone()); }
            IRInstruction::Call { result, callee, num_args } => {
                let start_idx = self.params.len().saturating_sub(*num_args);
                for i in 0..*num_args {
                    let arg = self.params[start_idx + i].clone();
                    if i < 6 {
                        let reg = abi::INTEGER_ARG_REGISTERS[i];
                        self.output.push_str(&ExpressionGenerator::load_operand(reg, &arg, &mut |o| sf.get_offset(o)));
                    }
                }
                if callee == "printf" || callee == "scanf" {
                    self.output.push_str("  mov eax, 0\n");
                }
                self.output.push_str(&format!("  call {}\n", callee));
                if let Some(r) = result {
                    self.output.push_str(&ExpressionGenerator::store_operand(r, "rax", &mut |o| sf.get_offset(o)));
                }
                self.params.truncate(start_idx);
            }
            IRInstruction::Equal { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::generate_comparison("sete", result, left, right, &mut |o| sf.get_offset(o)));
            }
            IRInstruction::NotEqual { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::generate_comparison("setne", result, left, right, &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Less { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::generate_comparison("setl", result, left, right, &mut |o| sf.get_offset(o)));
            }
            IRInstruction::LessEqual { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::generate_comparison("setle", result, left, right, &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Greater { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::generate_comparison("setg", result, left, right, &mut |o| sf.get_offset(o)));
            }
            IRInstruction::GreaterEqual { result, left, right } => {
                self.output.push_str(&ExpressionGenerator::generate_comparison("setge", result, left, right, &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Neg { result, operand } => {
                self.output.push_str(&ExpressionGenerator::load_operand("rax", operand, &mut |o| sf.get_offset(o)));
                self.output.push_str("  neg rax\n");
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Not { result, operand } => {
                self.output.push_str(&ExpressionGenerator::load_operand("rax", operand, &mut |o| sf.get_offset(o)));
                self.output.push_str("  xor rax, 1\n");
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Alloca { .. } => {
                // Stack is pre-allocated by StackFrame, so no instructions needed.
            }
            IRInstruction::Load { result, address } => {
                self.output.push_str(&ExpressionGenerator::load_operand("rax", address, &mut |o| sf.get_offset(o)));
                self.output.push_str("  mov rcx, [rax]\n");
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rcx", &mut |o| sf.get_offset(o)));
            }

            IRInstruction::Store { address, source } => {
                self.output.push_str(&ExpressionGenerator::load_operand("rax", address, &mut |o| sf.get_offset(o)));
                self.output.push_str(&ExpressionGenerator::load_operand("rcx", source, &mut |o| sf.get_offset(o)));
                self.output.push_str("  mov [rax], rcx\n");
            }
            IRInstruction::GetElementPtr { result, base, offset } => {
                let base_offset = sf.get_offset(base);
                self.output.push_str(&format!("  lea rax, [rbp{}]\n", if base_offset >= 0 { format!("+{}", base_offset) } else { base_offset.to_string() }));
                self.output.push_str(&ExpressionGenerator::load_operand("rcx", offset, &mut |o| sf.get_offset(o)));
                self.output.push_str("  shl rcx, 3\n");
                self.output.push_str("  add rax, rcx\n");
                self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
            }
            IRInstruction::Phi { result, sources } => {
                // Only emit a copy for non-literal sources whose stack slot differs from the result.
                // Literal sources are constant-propagation artifacts: the literal was already
                // materialized by a Move in the predecessor block. Emitting it here would
                // re-initialize the variable on every loop iteration (inside the loop-header label).
                let result_offset = sf.get_offset(result);
                for (op, _) in sources {
                    if let Operand::Literal { .. } | Operand::Label { .. } = op {
                        continue; // already handled by predecessor block's Move instruction
                    }
                    let source_offset = sf.get_offset(op);
                    if source_offset != result_offset {
                        self.output.push_str(&ExpressionGenerator::load_operand("rax", op, &mut |o| sf.get_offset(o)));
                        self.output.push_str(&ExpressionGenerator::store_operand(result, "rax", &mut |o| sf.get_offset(o)));
                    }
                }
            }
        }
    }

    fn static_operand_to_str(op: &Operand, sf: &mut StackFrame) -> String {
        match op {
            Operand::Literal { value } => value.clone(),
            Operand::Label { name } => name.clone(),
            _ => {
                let offset = sf.get_offset(op);
                format!("qword [rbp{}]", if offset >= 0 { format!("+{}", offset) } else { offset.to_string() })
            }
        }
    }
}
