use crate::ir::ir_instructions::{IRInstruction, Operand};
use crate::ir::basic_block::BasicBlock;
use crate::ir::ir_generator::FunctionMetadata;
use crate::codegen::{abi, label_manager::LabelManager, control_flow_generator::ControlFlowGenerator, stack_frame::StackFrame, optimizer::PeepholeOptimizer};
use std::collections::HashMap;

pub struct X86Generator {
    blocks: HashMap<String, BasicBlock>,
    functions: Vec<FunctionMetadata>,
    output: String,
    stack_frame: StackFrame,
    params: Vec<Operand>,
    strings: Vec<(String, String)>,
    reg_alloc: Option<crate::codegen::register_allocator::RegAlloc>,
}

impl X86Generator {
    pub fn new(blocks: HashMap<String, BasicBlock>, functions: Vec<FunctionMetadata>, strings: Vec<(String, String)>) -> Self {
        Self {
            blocks,
            functions,
            output: String::new(),
            stack_frame: StackFrame::new(),
            params: Vec::new(),
            strings,
            reg_alloc: None,
        }
    }

    pub fn generate(&mut self) -> String {
        self.output.push_str("; Generated by MiniCompiler\n");
        self.output.push_str("bits 64\n\n");
        
        self.output.push_str("extern print_int\n");
        self.output.push_str("extern read_int\n");
        self.output.push_str("extern printf\n");
        self.output.push_str("extern scanf\n");
        self.output.push_str("extern malloc\n");
        self.output.push_str("extern free\n");
        self.output.push_str("extern exit\n\n");

        self.output.push_str("section .text\n");

        let functions = self.functions.clone();
        for func in &functions {
            self.generate_function(func);
        }

        self.output.push_str("\nglobal _start\n");
        self.output.push_str("_start:\n");
        self.output.push_str("  call main\n");
        self.output.push_str("  mov rdi, rax\n");
        self.output.push_str("  mov rax, 60\n");
        self.output.push_str("  syscall\n");

        if !self.strings.is_empty() {
            self.output.push_str("\nsection .data\n");
            for (label, val) in &self.strings {
                self.output.push_str(&format!("{}: db {}, 0\n", label, val));
            }
        }

        PeepholeOptimizer::optimize(self.output.clone())
    }

    fn generate_function(&mut self, func: &FunctionMetadata) {
        let entry_label = format!("func_{}", func.name);
        self.output.push_str(&format!("\nglobal {}\n", func.name));
        self.output.push_str(&format!("{}:\n", func.name));

        self.stack_frame.reset();

        let reachable = self.get_reachable_blocks(&entry_label);
        
        // Run Register Allocation on ordered blocks (RPO) FIRST
        let mut ordered_blocks = Vec::new();
        for label in &reachable {
            if let Some(blk) = self.blocks.get(label) {
                ordered_blocks.push((label, blk));
            }
        }
        let reg_alloc = crate::codegen::register_allocator::RegisterAllocator::allocate(&ordered_blocks);
        self.reg_alloc = Some(reg_alloc);

        for p_name in &func.parameters {
            let op = Operand::Var { name: p_name.clone(), version: 0 };
            if self.reg_alloc.as_ref().and_then(|ra| ra.reg_for(&op)).is_none() {
                self.stack_frame.get_offset(&op);
            }
        }

        for blk_label in &reachable {
            let instructions = self.blocks.get(blk_label).map(|b| b.instructions.clone()).unwrap_or_default();
            for inst in instructions {
                self.track_operands(&inst);
            }
        }

        self.output.push_str("  push rbp\n");
        self.output.push_str("  mov rbp, rsp\n");

        let stack_size = self.stack_frame.aligned_size();
        if stack_size > 0 {
            self.output.push_str(&format!("  sub rsp, {}\n", stack_size));
        }

        // Save callee-saved registers that are used in allocation
        if let Some(ref ra) = self.reg_alloc {
            for reg in &ra.used_regs {
                self.output.push_str(&format!("  push {}\n", reg));
            }
        }

        for (i, p_name) in func.parameters.iter().enumerate() {
            let op = Operand::Var { name: p_name.clone(), version: 0 };
            if i < 6 {
                let reg = abi::INTEGER_ARG_REGISTERS[i];
                let inst_str = self.store_operand(&op, reg);
                self.output.push_str(&inst_str);
            } else {
                // Argument >= 6 is on the stack at [rbp + 16 + (i - 6) * 8]
                // We load it into rax and store it into the local operand (either reg or local stack slot)
                let offset = 16 + (i - 6) * 8;
                self.output.push_str(&format!("  mov rax, [rbp+{}]\n", offset));
                let inst_str = self.store_operand(&op, "rax");
                self.output.push_str(&inst_str);
            }
        }

        for blk_label in reachable {
            self.generate_block(&blk_label);
        }

        // Гарантируем наличие эпилога и возврата из функции (особенно для void функций или main)
        self.output.push_str(&format!(".{}_epilogue_fallback:\n", func.name));
        if let Some(ref ra) = self.reg_alloc {
            for reg in ra.used_regs.iter().rev() {
                self.output.push_str(&format!("  pop {}\n", reg));
            }
        }
        self.output.push_str("  mov rsp, rbp\n");
        self.output.push_str("  pop rbp\n");
        self.output.push_str("  ret\n");
    }

    fn track_operands(&mut self, inst: &IRInstruction) {
        let sf = &mut self.stack_frame;
        let reg_alloc = &self.reg_alloc;
        let mut track = |op: &Operand| {
            if let Operand::Var { .. } | Operand::Temp { .. } = op {
                if reg_alloc.as_ref().and_then(|ra| ra.reg_for(op)).is_none() {
                    sf.get_offset(op);
                }
            }
        };

        match inst {
            IRInstruction::Add { result, left, right } | IRInstruction::Sub { result, left, right } |
            IRInstruction::Mul { result, left, right } | IRInstruction::Div { result, left, right } |
            IRInstruction::Mod { result, left, right } |
            IRInstruction::And { result, left, right } | IRInstruction::Or { result, left, right } |
            IRInstruction::Xor { result, left, right } |
            IRInstruction::Equal { result, left, right } | IRInstruction::NotEqual { result, left, right } |
            IRInstruction::Less { result, left, right } | IRInstruction::LessEqual { result, left, right } |
            IRInstruction::Greater { result, left, right } | IRInstruction::GreaterEqual { result, left, right } => {
                track(result);
                track(left);
                track(right);
            }
            IRInstruction::Move { result, source: operand } => {
                track(result);
                track(operand);
            }
            IRInstruction::Not { result, operand } | IRInstruction::Neg { result, operand } => {
                track(result);
                track(operand);
            }
            IRInstruction::Call { result, num_args, .. } => {
                if let Some(r) = result { track(r); }
            }
            IRInstruction::Phi { result, sources } => {
                track(result);
                for (op, _) in sources { track(op); }
            }
            IRInstruction::Alloca { result, size } => {
                sf.allocate_array(result, *size);
            }
            IRInstruction::Load { result, address } => {
                track(result);
                track(address);
            }
            IRInstruction::Store { address, source } => {
                track(address);
                track(source);
            }
            IRInstruction::GetElementPtr { result, base, offset } => {
                track(result);
                track(base);
                track(offset);
            }
            IRInstruction::JumpIfTrue { condition, .. } | IRInstruction::JumpIfFalse { condition, .. } => {
                track(condition);
            }
            IRInstruction::Return { value: Some(op) } | IRInstruction::Param { value: op } => {
                track(op);
            }
            IRInstruction::Return { value: None } | IRInstruction::Jump { .. } => {}
        }
    }

    fn get_reachable_blocks(&self, start: &String) -> Vec<String> {
        let mut post_order: Vec<String> = Vec::new();
        let mut visited: std::collections::HashSet<String> = std::collections::HashSet::new();

        fn dfs(
            node: &str,
            blocks: &std::collections::HashMap<String, BasicBlock>,
            visited: &mut std::collections::HashSet<String>,
            post_order: &mut Vec<String>,
        ) {
            if !visited.insert(node.to_string()) { return; }
            if let Some(blk) = blocks.get(node) {
                for succ in blk.successors.iter().rev() {
                    if !succ.starts_with("func_") {
                        dfs(succ, blocks, visited, post_order);
                    }
                }
            }
            post_order.push(node.to_string());
        }

        dfs(start, &self.blocks, &mut visited, &mut post_order);

        post_order.reverse();
        post_order
    }

    fn reg_for(&self, op: &Operand) -> Option<&'static str> {
        self.reg_alloc.as_ref().and_then(|ra| ra.reg_for(op))
    }

    fn load_operand(&mut self, reg: &str, op: &Operand) -> String {
        if let Some(allocated_reg) = self.reg_for(op) {
            if allocated_reg == reg {
                String::new()
            } else {
                format!("  mov {}, {}\n", reg, allocated_reg)
            }
        } else {
            let offset = self.stack_frame.get_offset(op);
            match op {
                Operand::Literal { value } => format!("  mov {}, {}\n", reg, value),
                Operand::Label { name } => format!("  mov {}, {}\n", reg, name),
                _ => {
                    format!("  mov {}, [rbp{}]\n", reg, if offset >= 0 { format!("+{}", offset) } else { offset.to_string() })
                }
            }
        }
    }

    fn store_operand(&mut self, op: &Operand, reg: &str) -> String {
        if let Some(allocated_reg) = self.reg_for(op) {
            if allocated_reg == reg {
                String::new()
            } else {
                format!("  mov {}, {}\n", allocated_reg, reg)
            }
        } else {
            let offset = self.stack_frame.get_offset(op);
            format!("  mov [rbp{}], {}\n", if offset >= 0 { format!("+{}", offset) } else { offset.to_string() }, reg)
        }
    }

    fn operand_to_str(&mut self, op: &Operand) -> String {
        if let Some(allocated_reg) = self.reg_for(op) {
            allocated_reg.to_string()
        } else {
            match op {
                Operand::Literal { value } => value.clone(),
                Operand::Label { name } => name.clone(),
                _ => {
                    let offset = self.stack_frame.get_offset(op);
                    format!("qword [rbp{}]", if offset >= 0 { format!("+{}", offset) } else { offset.to_string() })
                }
            }
        }
    }

    fn generate_comparison(&mut self, set_inst: &str, result: &Operand, left: &Operand, right: &Operand) -> String {
        let mut output = self.load_operand("rax", left);
        if let Some(allocated_reg) = self.reg_for(right) {
            output.push_str(&format!("  cmp rax, {}\n", allocated_reg));
        } else {
            match right {
                Operand::Literal { value } => {
                    output.push_str(&format!("  cmp rax, {}\n", value));
                }
                _ => {
                    let offset = self.stack_frame.get_offset(right);
                    output.push_str(&format!("  cmp rax, [rbp{}]\n", if offset >= 0 { format!("+{}", offset) } else { offset.to_string() }));
                }
            }
        }
        output.push_str(&format!("  {} al\n", set_inst));
        output.push_str("  movzx rax, al\n");
        let store = self.store_operand(result, "rax");
        output.push_str(&store);
        output
    }

    fn generate_block(&mut self, label: &String) {
        self.output.push_str(&format!("{}:\n", LabelManager::block_label(label)));
        let insts = self.blocks.get(label).unwrap().instructions.clone();
        for inst in insts {
            self.generate_instruction(&inst);
        }
    }

    fn generate_instruction(&mut self, inst: &IRInstruction) {
        let mut code = String::new();
        match inst {
            IRInstruction::Add { result, left, right } => {
                let right_str = self.operand_to_str(right);
                let load = self.load_operand("rax", left);
                let store = self.store_operand(result, "rax");
                code.push_str(&load);
                code.push_str(&format!("  add rax, {}\n", right_str));
                code.push_str(&store);
            }
            IRInstruction::Sub { result, left, right } => {
                let right_str = self.operand_to_str(right);
                let load = self.load_operand("rax", left);
                let store = self.store_operand(result, "rax");
                code.push_str(&load);
                code.push_str(&format!("  sub rax, {}\n", right_str));
                code.push_str(&store);
            }
            IRInstruction::Mul { result, left, right } => {
                let right_str = self.operand_to_str(right);
                let load = self.load_operand("rax", left);
                let store = self.store_operand(result, "rax");
                code.push_str(&load);
                code.push_str(&format!("  imul rax, {}\n", right_str));
                code.push_str(&store);
            }
            IRInstruction::Div { result, left, right } => {
                let load = self.load_operand("rax", left);
                let store = self.store_operand(result, "rax");
                code.push_str(&load);
                
                let mut optimized = false;
                if let Operand::Literal { value } = right {
                    if let Ok(v) = value.parse::<i64>() {
                        if v > 0 && (v & (v - 1)) == 0 {
                            let shift = v.trailing_zeros();
                            code.push_str(&format!("  sar rax, {}\n", shift));
                            optimized = true;
                        }
                    }
                }
                
                if !optimized {
                    code.push_str("  cqo\n");
                    match right {
                        Operand::Literal { value } => {
                            code.push_str(&format!("  mov rcx, {}\n", value));
                            code.push_str("  idiv rcx\n");
                        }
                        _ => {
                            let right_str = self.operand_to_str(right);
                            code.push_str(&format!("  idiv {}\n", right_str));
                        }
                    }
                }
                code.push_str(&store);
            }
            IRInstruction::Mod { result, left, right } => {
                let load = self.load_operand("rax", left);
                let store = self.store_operand(result, "rdx");
                
                let mut optimized = false;
                if let Operand::Literal { value } = right {
                    if let Ok(v) = value.parse::<i64>() {
                        if v > 0 && (v & (v - 1)) == 0 {
                            code.push_str(&load);
                            code.push_str(&format!("  and rax, {}\n", v - 1));
                            let store_opt = self.store_operand(result, "rax");
                            code.push_str(&store_opt);
                            optimized = true;
                        }
                    }
                }

                if !optimized {
                    code.push_str(&load);
                    code.push_str("  cqo\n");
                    match right {
                        Operand::Literal { value } => {
                            code.push_str(&format!("  mov rcx, {}\n", value));
                            code.push_str("  idiv rcx\n");
                        }
                        _ => {
                            let right_str = self.operand_to_str(right);
                            code.push_str(&format!("  idiv {}\n", right_str));
                        }
                    }
                    code.push_str(&store);
                }
            }
            IRInstruction::And { result, left, right } => {
                let right_str = self.operand_to_str(right);
                let load = self.load_operand("rax", left);
                let store = self.store_operand(result, "rax");
                code.push_str(&load);
                code.push_str(&format!("  and rax, {}\n", right_str));
                code.push_str(&store);
            }
            IRInstruction::Or { result, left, right } => {
                let right_str = self.operand_to_str(right);
                let load = self.load_operand("rax", left);
                let store = self.store_operand(result, "rax");
                code.push_str(&load);
                code.push_str(&format!("  or rax, {}\n", right_str));
                code.push_str(&store);
            }
            IRInstruction::Xor { result, left, right } => {
                let right_str = self.operand_to_str(right);
                let load = self.load_operand("rax", left);
                let store = self.store_operand(result, "rax");
                code.push_str(&load);
                code.push_str(&format!("  xor rax, {}\n", right_str));
                code.push_str(&store);
            }
            IRInstruction::Move { result, source } => {
                if let Some(r_reg) = self.reg_for(result) {
                    let load = self.load_operand(r_reg, source);
                    code.push_str(&load);
                } else if let Some(s_reg) = self.reg_for(source) {
                    let store = self.store_operand(result, s_reg);
                    code.push_str(&store);
                } else {
                    if self.stack_frame.get_offset(result) == self.stack_frame.get_offset(source) { return; }
                    let load = self.load_operand("rax", source);
                    let store = self.store_operand(result, "rax");
                    code.push_str(&load);
                    code.push_str(&store);
                }
            }
            IRInstruction::Return { value } => {
                if let Some(v) = value {
                    let load = self.load_operand("rax", v);
                    code.push_str(&load);
                }
                if let Some(ref ra) = self.reg_alloc {
                    for reg in ra.used_regs.iter().rev() {
                        code.push_str(&format!("  pop {}\n", reg));
                    }
                }
                code.push_str("  mov rsp, rbp\n  pop rbp\n  ret\n");
            }
            IRInstruction::Jump { label } => {
                code.push_str(&ControlFlowGenerator::generate_jump(label));
            }
            IRInstruction::JumpIfTrue { condition, label } => {
                let load = self.load_operand("rax", condition);
                code.push_str(&load);
                code.push_str(&ControlFlowGenerator::generate_jump_if("rax", label, true));
            }
            IRInstruction::JumpIfFalse { condition, label } => {
                let load = self.load_operand("rax", condition);
                code.push_str(&load);
                code.push_str(&ControlFlowGenerator::generate_jump_if("rax", label, false));
            }
            IRInstruction::Param { value } => { self.params.push(value.clone()); }
            IRInstruction::Call { result, callee, num_args } => {
                let start_idx = self.params.len().saturating_sub(*num_args);
                
                // For System V AMD64 ABI, arguments 7+ are pushed to the stack in reverse order
                if *num_args > 6 {
                    for i in (6..*num_args).rev() {
                        let arg = self.params[start_idx + i].clone();
                        let load = self.load_operand("rax", &arg);
                        code.push_str(&load);
                        code.push_str("  push rax\n");
                    }
                }
                
                // First 6 arguments are loaded into registers
                for i in 0..std::cmp::min(6, *num_args) {
                    let arg = self.params[start_idx + i].clone();
                    let reg = abi::INTEGER_ARG_REGISTERS[i];
                    let load = self.load_operand(reg, &arg);
                    code.push_str(&load);
                }
                
                if callee == "printf" || callee == "scanf" {
                    code.push_str("  mov eax, 0\n");
                }
                code.push_str(&format!("  call {}\n", callee));
                
                // Clean up the stack if we pushed arguments
                if *num_args > 6 {
                    let stack_cleanup = (*num_args - 6) * 8;
                    code.push_str(&format!("  add rsp, {}\n", stack_cleanup));
                }

                if let Some(r) = result {
                    let store = self.store_operand(r, "rax");
                    code.push_str(&store);
                }
                self.params.truncate(start_idx);
            }
            IRInstruction::Equal { result, left, right } => {
                let comparison = self.generate_comparison("sete", result, left, right);
                code.push_str(&comparison);
            }
            IRInstruction::NotEqual { result, left, right } => {
                let comparison = self.generate_comparison("setne", result, left, right);
                code.push_str(&comparison);
            }
            IRInstruction::Less { result, left, right } => {
                let comparison = self.generate_comparison("setl", result, left, right);
                code.push_str(&comparison);
            }
            IRInstruction::LessEqual { result, left, right } => {
                let comparison = self.generate_comparison("setle", result, left, right);
                code.push_str(&comparison);
            }
            IRInstruction::Greater { result, left, right } => {
                let comparison = self.generate_comparison("setg", result, left, right);
                code.push_str(&comparison);
            }
            IRInstruction::GreaterEqual { result, left, right } => {
                let comparison = self.generate_comparison("setge", result, left, right);
                code.push_str(&comparison);
            }
            IRInstruction::Neg { result, operand } => {
                let load = self.load_operand("rax", operand);
                let store = self.store_operand(result, "rax");
                code.push_str(&load);
                code.push_str("  neg rax\n");
                code.push_str(&store);
            }
            IRInstruction::Not { result, operand } => {
                let load = self.load_operand("rax", operand);
                let store = self.store_operand(result, "rax");
                code.push_str(&load);
                code.push_str("  xor rax, 1\n");
                code.push_str(&store);
            }
            IRInstruction::Alloca { .. } => {}
            IRInstruction::Load { result, address } => {
                let addr_reg = if let Some(reg) = self.reg_for(address) {
                    reg.to_string()
                } else {
                    let load = self.load_operand("rax", address);
                    code.push_str(&load);
                    "rax".to_string()
                };
                if let Some(r_reg) = self.reg_for(result) {
                    code.push_str(&format!("  mov {}, [{}]\n", r_reg, addr_reg));
                } else {
                    let store = self.store_operand(result, "rcx");
                    code.push_str(&format!("  mov rcx, [{}]\n", addr_reg));
                    code.push_str(&store);
                }
            }
            IRInstruction::Store { address, source } => {
                let addr_reg = if let Some(reg) = self.reg_for(address) {
                    reg.to_string()
                } else {
                    let load = self.load_operand("rax", address);
                    code.push_str(&load);
                    "rax".to_string()
                };
                let src_reg = if let Some(reg) = self.reg_for(source) {
                    reg.to_string()
                } else {
                    let load = self.load_operand("rcx", source);
                    code.push_str(&load);
                    "rcx".to_string()
                };
                code.push_str(&format!("  mov [{}], {}\n", addr_reg, src_reg));
            }
            IRInstruction::GetElementPtr { result, base, offset } => {
                let base_offset = self.stack_frame.get_offset(base);
                let load = self.load_operand("rcx", offset);
                let store = self.store_operand(result, "rax");
                code.push_str(&format!("  lea rax, [rbp{}]\n", if base_offset >= 0 { format!("+{}", base_offset) } else { base_offset.to_string() }));
                code.push_str(&load);
                code.push_str("  shl rcx, 3\n");
                code.push_str("  add rax, rcx\n");
                code.push_str(&store);
            }
            IRInstruction::Phi { .. } => {
                // Resolved at compile time by assigning all versions of the same variable to the same register or stack slot.
            }
        }
        self.output.push_str(&code);
    }
}
