; Generated by MiniCompiler
bits 64

extern print_int
extern read_int
extern printf
extern scanf
extern malloc
extern free
extern exit

section .text

global main
main:
  push rbp
  mov rbp, rsp
  sub rsp, 16
.func_main:
.then_1:
  mov rax, 10
  mov rsp, rbp
  pop rbp
  ret
  jmp .end_if_2
.else_3:
  mov rax, 20
  mov rsp, rbp
  pop rbp
  ret
.end_if_2:
.main_epilogue_fallback:
  mov rsp, rbp
  pop rbp
  ret

global _start
_start:
  call main
  mov rdi, rax
  mov rax, 60
  syscall